openapi: 3.0.0
info:
  title: Saxo Bank API
  version: Production
  x-audience: company-internal
servers:
- url: /
paths:
  /account:
    post:
      summary: Make a payment to specified account
      operationId: updateAccount
      responses:
        "405":
          description: Invalid input
components: {}
